name: Verifying Calibration

on: 
  push:
    paths:
      - 'redo2/ProductDatabase/birther'
  pull_request:
    paths:
      - 'redo2/ProductDatabase/birther'

jobs:
  Tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Files
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install endaq.ide
        run: pip install endaq.ide endaq.calc
      - name: Install pytest
        run: python -m pip install pytest pytest-lazy-fixture
      - name: Run Pytest
        working-directory: ProductDatabase
        run: python -m pytest
      - name: Print job status
        run: echo "Job status - ${{ job.status }}"
