name: Verifying Calibration

on: [push, pull_request]

jobs:
  Tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Files
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install endaq.ide
        run: pip install endaq.ide
      - name: Install pytest
        run: python -m pip install pytest pytest-lazy-fixture
      - name: Run Pytest
        working-directory: ProductDatabase
        run: python -m pytest birther\test_cal.py
      - name: Print job status
        run: echo "Job status - ${{ job.status }}"
